kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}-dmp-gateway-{{ .Values.dmp.tenant.code }}"
  labels:
    app: "{{ .Release.Name }}-dmp-gateway-{{ .Values.dmp.tenant.code }}"
    # health check labels.
    dmp.daocloud.io/app: "dmp-gateway-{{ .Values.dmp.tenant.code }}"
    dmp.daocloud.io/gateway: "{{ .Values.dmp.tenant.code }}"
spec:
  replicas: {{ .Values.dmp.tenant.gateway.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-dmp-gateway-{{ .Values.dmp.tenant.code }}"
  template:
    metadata:
      name: "{{ .Release.Name }}-dmp-gateway-{{ .Values.dmp.tenant.code }}"
      labels:
        app: "{{ .Release.Name }}-dmp-gateway-{{ .Values.dmp.tenant.code }}"
    spec:
      volumes:
        - name: envoy-log
          emptyDir: {}
      containers:
        - name: "{{ .Release.Name }}-dmp-envoy-{{ .Values.dmp.tenant.code }}"
          image: {{ .Values.dmp.tenant.gateway.image.envoy.repository }}:{{ .Values.dmp.tenant.gateway.image.envoy.tag }}
          imagePullPolicy: {{ .Values.dmp.tenant.gateway.image.envoy.pullPolicy }}
          ports:
            - name: envoy-admin
              containerPort: 9901
              protocol: TCP
            - name: l-10000
              containerPort: 10000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-dmp-tenant-config-{{ .Values.dmp.tenant.code }}"
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          volumeMounts:
            - name: envoy-log
              mountPath: /tmp/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: "{{ .Release.Name }}-dmp-fluentd-{{ .Values.dmp.tenant.code }}"
          image: {{ .Values.dmp.tenant.gateway.image.fluentd.repository }}:{{ .Values.dmp.tenant.gateway.image.fluentd.tag }}
          imagePullPolicy: {{ .Values.dmp.tenant.gateway.image.fluentd.pullPolicy }}
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-dmp-tenant-config-{{ .Values.dmp.tenant.code }}"
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          volumeMounts:
            - name: envoy-log
              mountPath: /tmp/
        - name: "{{ .Release.Name }}-dmp-thor-{{ .Values.dmp.tenant.code }}"
          image: {{ .Values.dmp.tenant.gateway.image.thor.repository }}:{{ .Values.dmp.tenant.gateway.image.thor.tag }}
          imagePullPolicy: {{ .Values.dmp.tenant.gateway.image.thor.pullPolicy }}
          ports:
            - name: thor-api
              containerPort: 9876
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"

