apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-daoshop-review
  labels:
    app: {{ .Release.Name }}-daoshop-review
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-daoshop-review
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-daoshop-review
        dx.daocloud.io/env-id: {{ .Values.tenant.code }}
        dx.daocloud.io/service-name: {{ .Release.Name }}-daoshop-review
    spec:
      containers:
        - image: {{ .Values.daoshop.review.image.repository }}:{{ .Values.daoshop.review.image.tag }}
          name: {{ .Release.Name }}-daoshop-review
          resources:
{{ toYaml .Values.daoshop.review.image.resources | indent 12 }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-daoshop-config-{{ .Values.tenant.code }}"
          env:
            - name: SERVICE_INSTANCE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: DX_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: DX_ENV_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: SW_AGENT_KUBE_NS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
