apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Release.Name }}-dmp-skywalking-oap"
  name: "{{ .Release.Name }}-dmp-config-twice"
data:
  K8S_SERVER: {{ .Values.external.k8sServer }}
  K8S_TOKEN: {{ .Values.external.k8sToken }}
