apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Release.Name }}-dmp-skywalking-oap"
  name: "{{ .Release.Name }}-dmp-config-ui"
data:
  TRACE_URL: "http://{{ .Release.Name }}-dmp-sw-query-server:12801"
  CONFIG_CENTER_URL:  "http://{{ .Release.Name }}-dmp-apollo-adminservice:8090"
  FATE_URL: "http://{{ .Release.Name }}-dmp-fate:9056"
  MONITOR_URL: {{ .Values.dmp.configmap.fateNodePortUrl }}
  TWICE_URL: "http://{{ .Release.Name }}-dmp-twice:8765"
  HELP_URL: {{ .Values.dmp.configmap.helpDocsUrl }}