apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-daoshop-ui
  labels:
    app: {{ .Release.Name }}-daoshop-ui
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-daoshop-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-daoshop-ui
    spec:
      containers:
        - image: {{ .Values.daoshop.ui.image.repository }}:{{ .Values.daoshop.ui.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}-daoshop-ui
          resources:
{{ toYaml .Values.daoshop.ui.image.resources | indent 12 }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-daoshop-config-{{ .Values.tenant.code }}"
          env:
            - name: APP_NAME
              value: 'ww'
            - name: DX_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''dx.daocloud.io/service-name'']'
            - name: DX_ENV_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''dx.daocloud.io/env-id'']'
            - name: SW_AGENT_KUBE_NS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
