apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dmp-skywalking-oap"
spec:
  type: {{ .Values.dmp.skywalkingOap.service.type }}
  ports:
    - port: 12800
      name: rest
    - port: 11800
      name: grpc
  selector:
    app: "{{ .Release.Name }}-dmp-skywalking-oap"
