apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dmp-twice"
spec:
  type: {{ .Values.dmp.twice.service.type }}
  ports:
    - port: 8765
      name: api
    - port: 7000
      name: gateway
  selector:
    dx.daocloud.io/service-name: dmp-twice
