dmp:
  tenant:
    code: "test" # !!! 注意要更改
    envoyLoglevel: "INFO"
    swOapHost: "dmp-management-release-dmp-skywalking-oap.dmp.svc"
    swOapPort: "11800"
    twiceHost: "dmp-management-release-dmp-twice.dmp.svc"
    twicePort: "7000"
    fateServer: "ws://10.99.100.106:32354" # 该地址要写客户端浏览器能访问到的NodePort地址
    adminIP: "0.0.0.0"
    collectLogByKafka: "false"
    esAddrs: "elasticsearch-master.dmp.svc:9200" # 可以写多个地址，用逗号隔开，如果collectLogByKafka为false，填写该地址
    esUsername: ""
    esPassword: ""
    esShards: "3" #网关 ES 索引主分片数，默认 3
    esReplicas: "0" #网关 ES 索引副分片数，默认 0
    kafkaAddrs: "" # 如果collectLogByKafka为true，则填写该地址
    gateway:
      replicas: 1
      service:
        type: NodePort
      image:
        envoy:
          repository: registry.dx.io/dx-pilot/dmp-envoy
          tag: develop-7074d4b  # Must be set explicitly
          pullPolicy: IfNotPresent
        fluentd:
          repository: registry.dx.io/dx-pilot/dmp-fluentd
          tag: develop-f488ed2  # Must be set explicitly
          pullPolicy: IfNotPresent
          livenessProbe:
            enabled: true
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          ## Configure extra options for readiness probe
          ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
          ## @param forwarder.readinessProbe.enabled Enable readinessProbe
          ## @param forwarder.readinessProbe.httpGet.path Request path for readinessProbe
          ## @param forwarder.readinessProbe.httpGet.port Port for readinessProbe
          ## @param forwarder.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
          ## @param forwarder.readinessProbe.periodSeconds Period seconds for readinessProbe
          ## @param forwarder.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
          ## @param forwarder.readinessProbe.failureThreshold Failure threshold for readinessProbe
          ## @param forwarder.readinessProbe.successThreshold Success threshold for readinessProbe
          ##
          readinessProbe:
            enabled: true
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
        thor:
          repository: registry.dx.io/dx-pilot/dmp-thor
          tag: develop-04211f9  # Must be set explicitly
          pullPolicy: IfNotPresent


############
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
