dmp:
  tenant:
    code: "test" # !!! 注意要更改
    envoyLoglevel: "INFO"
    swOapHost: "dmp-management-release-dmp-skywalking-oap.dmp.svc"
    swOapPort: "11800"
    twiceHost: "dmp-management-release-dmp-twice.dmp.svc"
    twicePort: "7000"
    fateServer: "ws://10.99.100.106:32354"
    esHost: "elasticsearch-master.dmp.svc"
    esPort: "9200"
    adminIP: "0.0.0.0"
    gateway:
      replicas: 1
      service:
        type: NodePort
      image:
        envoy:
          repository: registry.dx.io/dx-pilot/dmp-envoy
          tag: develop-7074d4b  # Must be set explicitly
          pullPolicy: IfNotPresent
        fluentd:
          repository: registry.dx.io/dx-pilot/dmp-fluentd
          tag: develop-f488ed2  # Must be set explicitly
          pullPolicy: IfNotPresent
        thor:
          repository: registry.dx.io/dx-pilot/dmp-thor
          tag: develop-04211f9  # Must be set explicitly
          pullPolicy: IfNotPresent

############
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
