apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-dmp-fate"
  labels:
    dx.daocloud.io/service-name: dmp-fate
spec:
  replicas: {{ .Values.dmp.fate.replicas }}
  selector:
    matchLabels:
      dx.daocloud.io/service-name: dmp-fate
  template:
    metadata:
      labels:
        dx.daocloud.io/service-name: dmp-fate
    spec:
      containers:
        - image: {{ .Values.dmp.fate.image.repository }}:{{ .Values.dmp.fate.image.tag }}
          name: "{{ .Release.Name }}-dmp-dmp-fate"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8998
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8998
              scheme: HTTP
            initialDelaySeconds: 95
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{ toYaml .Values.dmp.fate.image.resources | indent 12 }}
          ports:
            - containerPort: 9056
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-dmp-config-common"
          env:
            - name: DMP_LOGS_TOPIC
              value: {{ .Values.dmp.fate.logTpoic }}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
